---
# when using the default proxy server port
# * for devolopment

# local_backend: true

# backend:
#   name: git-gateway

# # * for devolopment

# ! for Production

backend:
  name: github
  repo: sanabel-al-firdaws/sanabel-al-firdaws.github.io
  branch: main
  base_url: https://sveltia-cms-auth.abdullhakim-sami.workers.dev/

# ! for Production
# i18n:
#   # Required and can be one of multiple_folders, multiple_files or single_file
#   # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
#   # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
#   # single_file - persists a single file in `<folder>/<slug>.<extension>`
#   structure: multiple_folders

#   # Required - a list of locales to show in the editor UI
#   locales: [ar, en]

#   # Optional, defaults to the first item in locales.
#   # The locale to be used for fields validation and as a baseline for the entry.
#   # defaultLocale: ar
collections:

  - label: باب الإسلام
    name: al-islam
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/ar/aqida/al-islam
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    nested:
      depth: 100 # max depth to show in the collection tree
  - label: باب الإيمان
    name: al-eman
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/ar/aqida/al-eman
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    nested:
      depth: 100 # max depth to show in the collection tree
  - label: باب الإحسان
    name: al-ehsan
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        widget: string
      
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/ar/aqida/al-ehsan
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    nested:
      depth: 100 # max depth to show in the collection tree

site_url: https://sanabel-al-firdaws.github.io/

logo_url : /favicon.svg
media_folder: public/img



  # - label: "منهاج المسلم"
  #   name: "docs"
  #   folder: "content/docs"
  #   create: true
  #   fields:
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     # - { label: "Featured Image", name: "thumbnail", widget: "image" }
  #     - { label: "Body", name: "body", widget: "markdown" }# backend:
