---
# when using the default proxy server port
# * for devolopment

# local_backend: true

# backend:
#   name: git-gateway
# editor:
#   preview: false
#   frame: false

# * for devolopment

# * for Production

publish_mode: editorial_workflow
backend:
  name: github
  repo: sanabel-al-firdaws/sanabel-al-firdaws.github.io
  branch: main
  auth_scope: repo
  open_authoring: true
  base_url: https://sveltia-cms-auth.abdullhakim-sami.workers.dev
  commit_messages:
    create: "{{slug}} أضفت {{collection}}"
    update: "{{slug}} غيرت على {{collection}}"
    delete: "{{slug}} حذفت {{collection}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"
  
# * for Production
disable_local_backup: true
collections:
  - label: كتاب العقيدة
    name: aqida
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
        show_raw: true

      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        hint: الرابط لازم يكون بالانجليزي وبدون فواصل
        widget: string

      - label: تاريخ تعديل المقال 
        name: lastUpdated
        widget: 'datetime' # e.g. 24.12.2022
        time_format: false
        format: 'yyyy-MM-dd' # e.g. 2022-12-24
      - label: القائمة
        widget: object
        name: sidebar
        fields:
          -  name: order
             label: الترتيب
             widget: number
             default: 1
             value_type: int
             min: 1
     


      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: /src/content/docs/ar/aqida

  - label: كتاب الحديث
    name: hadith
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
        show_raw: true
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        hint: الرابط لازم يكون بالانجليزي وبدون فواصل
      - label: تاريخ تعديل المقال 
        name: lastUpdated
        widget: 'datetime' # e.g. 24.12.2022
        time_format: false
        format: 'yyyy-MM-dd' # e.g. 2022-12-24
      - label: القائمة
        widget: object
        name: sidebar
        fields:
          -  name: order
             label: الترتيب
             widget: number
             default: 1
             value_type: int
             min: 1
     
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: /src/content/docs/ar/hadith/
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'
  - label: باب الإسلام
    name: al-islam
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
        show_raw: true

      - label: عنوان المقال
        name: title
        widget: string
      - label: رابط المقال
        name: filename
        hint: الرابط لازم يكون بالانجليزي وبدون فواصل
      - label: تاريخ تعديل المقال 
        name: lastUpdated
        widget: 'datetime' # e.g. 24.12.2022
        time_format: false
        format: 'yyyy-MM-dd' # e.g. 2022-12-24
      - label: القائمة
        widget: object
        name: sidebar
        fields:
          -  name: order
             label: الترتيب
             widget: number
             default: 1
             value_type: int
             min: 1
     
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: /src/content/docs/ar/aqida/al-islam
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree
  - label: باب الإيمان
    name: al-eman
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
        show_raw: true

  
      - label: عنوان المقال
        name: title
        widget: string

      - label: رابط المقال
        name: filename
        hint: الرابط لازم يكون بالانجليزي وبدون فواصل
        widget: string
      - label: تاريخ تعديل المقال 
        name: lastUpdated
        widget: 'datetime' # e.g. 24.12.2022
        time_format: false
        format: 'yyyy-MM-dd' # e.g. 2022-12-24
      - label: القائمة
        widget: object
        name: sidebar
        fields:
          -  name: order
             label: الترتيب
             widget: number
             default: 1
             value_type: int
             min: 1
     
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/ar/aqida/al-eman
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'



  - label: باب الإحسان
    name: al-ehsan
    create: true
  
    fields:
      - label: محتوى المقال
        name: body
        widget: markdown
        show_raw: true
      - label: عنوان المقال
        name: title
        widget: string
      - label: رابط المقال
        name: filename
        hint: الرابط لازم يكون بالانجليزي وبدون فواصل
      - label: تاريخ تعديل المقال 
        name: lastUpdated
        widget: 'datetime' # e.g. 24.12.2022
        time_format: false
        format: 'yyyy-MM-dd' # e.g. 2022-12-24
      - label: القائمة
        widget: object
        name: sidebar
        fields:
          -  name: order
             label: الترتيب
             widget: number
             default: 1
             value_type: int
             min: 1
     
      # - label: العلامات
      #   name: tags
      #   required: false
      #   widget: list

    # path: "{{slug}}"
    slug: "{{fields.filename}}"
    extension: mdoc
    format: frontmatter
    folder: src/content/docs/ar/aqida/al-ehsan
    # path: '/aqida/al-ehsan/{{fields.path}}.{{extension}}'


    # nested:
    #   depth: 100 # max depth to show in the collection tree



site_url: https://sanabel-al-firdaws.github.io/

logo_url : /favicon.svg
media_folder: public/img
